server {
    listen 80;
    root /usr/share/nginx/html;

    location / {
        index index.html;
        try_files $uri $uri/ /index.html;

        # HTML 绝不强缓存，确保每次加载最新 JS 包
        if ($request_filename ~* .*\.(html|htm)$) {
            add_header Cache-Control "no-cache, no-store, must-revalidate";
            add_header Pragma "no-cache";
            add_header Expires "0";
        }
    }
}
