name: ZeroQuant Web CI/CD Workflow

on:
  push:
    branches: [ "auto", "main", "master" ]
  pull_request:
    branches: [ "auto", "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20.x

    - name: Install web dependencies
      run: npm ci

    - name: Build web production bundle
      run: npm run build
